name: Build Game

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Raylib
        run: |
          sudo apt update
          sudo apt install -y build-essential raylib libraylib-dev

      - name: Build Project
        run: |
          make PLATFORM=PLATFORM_DESKTOP BUILD_MODE=RELEASE

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Raylib
        run: |
          choco install -y mingw
          git clone https://github.com/raysan5/raylib.git C:/raylib/raylib
          cd C:/raylib/raylib/src && mingw32-make PLATFORM=PLATFORM_DESKTOP

      - name: Build Project
        run: |
          make PLATFORM=PLATFORM_DESKTOP BUILD_MODE=RELEASE
