name: Autobuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up MinGW environment
        shell: cmd
        run: |
          choco install mingw -y
          echo Adding MinGW to PATH
          setx PATH "%PATH%;C:\tools\mingw64\bin"

      - name: Set up raylib
        shell: cmd
        run: |
          mkdir C:\raylib
          curl -L https://github.com/raysan5/raylib/archive/refs/tags/4.5.0.zip -o raylib.zip
          tar -xf raylib.zip -C C:\raylib --strip-components=1

      - name: Build project
        shell: bash
        env:
          RAYLIB_PATH: C:/raylib
          COMPILER_PATH: C:/tools/mingw64/bin
        run: |
          mingw32-make clean
          mingw32-make all

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/bin/
